### ISSUE TITLE
Feature: tokenCast owned default wallet or similar?

### ISSUE THREAD

**Issue by obxium** [codyborn/tokenCast#1]
This is an amazing project, so thanks for starting it!

It could be cool and useful to establish a default wallet as part of a set of defaults that tokenCast can use upon startup so it can be faster to bootstrap a more plug and play experience, which could be handy for mass deployments in large settings like conferences, etc.

This should be something that is configured in the code and the wallet should be owned by the project maintainer / organization.

You could have a call to artists to submit art that populates this default wallet. This would create exposure for the artists and provide a nice set of initial art in the default wallet so that folks who just want to quickly spin up a tokenCast don't have to worry about already having a wallet to point it to.

I'd be happy to contribute a piece of my own art to this tokenCast default wallet.

You could even have auctions on some of the artworks in the wallet for charity, to help fund development, presence at conferences, etc.

You might also consider extending the concept to a list of built in wallet addresses that are popular or well known, for example the SuperRare Vault wallet, which is packed full of amazing art.

Keep up the great work!

**Comment by codyborn** [comment]
That's a great idea @obxium! It provides an easy way to try it out before purchasing your own artwork. My only concern is that anyone would be able to send art to the default wallet which could lead to spam or other inappropriate content being displayed to folks. We could add the feature, and if this starts happening then we could create an exception list where we only shown known good content. WDYT?

**Comment by obxium** [comment]
Cool! I think implementing a whitelist of NFTs to be shown from the default wallet would handle the spam aspect from the outset. As a side benefit, once you had this large pool of NFTs you could use them for fun stuff like giveaways, inviting new artists to submit works for special events, contests and so on.

**Comment by codyborn** [comment]
@obxium Just deployed the feature! 🎉 Let me know what you think
https://youtu.be/sR8JqHTOMTg
