### ISSUE TITLE
Video bugfix

### ISSUE THREAD

**Issue by DurinDwarf** [codyborn/tokenCast#2]
Correct a display bug when a video is rotated.
Delete the «muted» attribute.

tokenCast\TokenCastWebApp\Views\Device\Index.cshtml

line 156: `<video v-if="isVideo" style="height:100%; width:100%;" loop autoplay>`

**Comment by codyborn** [comment]
Addressed in https://github.com/codyborn/tokenCast/commit/aa4a8a5e443be1fa24a0f46f025dd507191453f8
