### ISSUE TITLE
Rotated video : display bug

### ISSUE THREAD

**Issue by DurinDwarf** [codyborn/tokenCast#3]
When a video is rotated, its width is cropped on the right side.

Modification suggested in tokenCast\TokenCastWebApp\Views\Device\Index.cshtml
width=100% instead of width=auto

line 156: `<video v-if="isVideo" style="height:100%; width:100%;" loop autoplay>`

**Comment by codyborn** [comment]
Fixed in 2ea9ddae5c4a7a4e938bd829326a21c37c818335
