### ISSUE TITLE
does TokenCast keep a copy of the high resolution artwork in case the platform goes out of business

### ISSUE THREAD

**Issue by bardionson** [codyborn/tokenCast#5]
Does TokenCast retrieve the high resolution version stored by the platform like SuperRare, MakersPlace, KnownOrigin or elementum.art. These platforms store the high resolution image in IPFS or in an S3 bucket or other proprietary system.

Does TokenCast get the low resolution thumbnail from OpenSea or the full version Mp4 or jpeg from the backing storage system?

Does TokenCast store a copy of the high resolution image or movie on the device for local storage? I have had images I purchased disappear when the marketplace shut down. They turned off their storage system or it expired from IPFS. It would be nice if a digital frame could store a copy in case this happens.

thank you

**Comment by codyborn** [comment]
Hi @bardionson! Tokencast pulls the image from the original source defined in the NFT json. Tokencast queries OpenSea API ([example](https://api.opensea.io/api/v1/assets/?owner=0xEeA95EdFC25F15C0c44d4081BBd85026ba298Dc6)) to get the image sources and uses those for displaying the image. Tokencast does not keep a copy of the image. For the reason you mentioned, artists should choose a hosting solution like IPFS to prevent the image from being lost if the centralized hosting provider shuts down. There are a set of IPFS pinning services that you can use to make sure the content never expires from IPFS: https://docs.ipfs.io/concepts/persistence/
